wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1673615483
    t:
      1:
      - 1
      - 53
      - 55
      3:
      - 17
      4: 3.9.2
      5: 0.12.21
      8:
      - 8
      - 9
biased:
  desc: null
  value: 1
k:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0001
tr_batch_size:
  desc: null
  value: 512
wd:
  desc: null
  value: 0.0005
